<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>askomdchatomationtesting</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.release>17</maven.compiler.release>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <selenium.version>4.16.1</selenium.version>
        <cucumber.version>7.15.0</cucumber.version>
        <testng.version>7.9.0</testng.version>
        <webdrivermanager.version>5.6.3</webdrivermanager.version>

        <!-- >>>>>>>>>>>>>>>>>>>>>> ALLURE COMMENT <<<<<<<<<<<<<<<<<<<< -->
        <allure.version>2.24.0</allure.version>
        <aspectj.version>1.9.20.1</aspectj.version>
        <!-- >>>>>>>>>>>>>>>>>>>>>> ALLURE COMMENT <<<<<<<<<<<<<<<<<<<< -->
    </properties>

    <dependencies>

        <!-- EXTENT REPORT -->
        <dependency>
            <groupId>com.aventstack</groupId>
            <artifactId>extentreports</artifactId>
            <version>5.1.1</version>
        </dependency>

        <dependency>
            <groupId>tech.grasshopper</groupId>
            <artifactId>extentreports-cucumber7-adapter</artifactId>
            <version>1.14.0</version>
        </dependency>

        <!-- >>>>>>>>>>>>>>>>>>>>>> ALLURE COMMENT <<<<<<<<<<<<<<<<<<<< -->
        <!-- Allure integration with Cucumber 7 -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-cucumber7-jvm</artifactId>
            <version>${allure.version}</version>
        </dependency>

        <!-- Allure integration with TestNG -->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-testng</artifactId>
            <version>${allure.version}</version>
        </dependency>

        <!-- Required for Allure TestNG (AspectJ weaving) -->
        <dependency>
            <groupId>org.aspectj</groupId>
            <artifactId>aspectjweaver</artifactId>
            <version>${aspectj.version}</version>
            <scope>runtime</scope>
        </dependency>
        <!-- >>>>>>>>>>>>>>>>>>>>>> ALLURE COMMENT <<<<<<<<<<<<<<<<<<<< -->
<!--        Monte creates the video file on your hard drive.-->
        <dependency>
            <groupId>com.github.stephenc.monte</groupId>
            <artifactId>monte-screen-recorder</artifactId>
            <version>0.7.7.0</version>
        </dependency>
<!--        Allure Java Commons picks up that file and attaches it to the report.-->
        <dependency>
            <groupId>io.qameta.allure</groupId>
            <artifactId>allure-java-commons</artifactId>
            <version>${allure.version}</version>
        </dependency>
        <!-- CUCUMBER -->
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-testng</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- SELENIUM -->
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>

        <!-- TESTNG -->
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>${testng.version}</version>
            <scope>test</scope>
        </dependency>

        <!-- UTILITIES -->
        <dependency>
            <groupId>io.github.bonigarcia</groupId>
            <artifactId>webdrivermanager</artifactId>
            <version>${webdrivermanager.version}</version>
        </dependency>

        <dependency>
            <groupId>net.datafaker</groupId>
            <artifactId>datafaker</artifactId>
            <version>2.1.0</version>
        </dependency>

        <dependency>
            <groupId>commons-io</groupId>
            <artifactId>commons-io</artifactId>
            <version>2.21.0</version>
        </dependency>

    </dependencies>

    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <release>17</release>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>3.2.5</version>
                <configuration>
                    <includes>
                        <include>**/runnerClass.java</include>
                    </includes>
                    <systemPropertyVariables>
                        <headless>${headless}</headless>
                    </systemPropertyVariables>
                    <argLine>
                        -javaagent:"${settings.localRepository}/org/aspectj/aspectjweaver/${aspectj.version}/aspectjweaver-${aspectj.version}.jar"
                    </argLine>
                </configuration>
            </plugin>

            <!-- MASTERTHOUGHT REPORT -->
            <plugin>
                <groupId>net.masterthought</groupId>
                <artifactId>maven-cucumber-reporting</artifactId>
                <version>5.7.8</version>
                <executions>
                    <execution>
                        <id>execution</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <projectName>Cucumber Test Report</projectName>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <inputDirectory>${project.build.directory}</inputDirectory>
                            <jsonFiles>
                                <param>**/*.json</param>
                            </jsonFiles>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

        </plugins>
    </build>

</project>


<!--<?xml version="1.0" encoding="UTF-8"?>-->
<!--<project xmlns="http://maven.apache.org/POM/4.0.0"-->
<!--         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"-->
<!--         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0-->
<!--         http://maven.apache.org/xsd/maven-4.0.0.xsd">-->

<!--    <modelVersion>4.0.0</modelVersion>-->

<!--    <groupId>org.example</groupId>-->
<!--    <artifactId>askomdchatomationtesting</artifactId>-->
<!--    <version>1.0-SNAPSHOT</version>-->

<!--    <properties>-->
<!--        &lt;!&ndash; ✅ Java 17 (Stable LTS) &ndash;&gt;-->
<!--        <maven.compiler.source>17</maven.compiler.source>-->
<!--        <maven.compiler.target>17</maven.compiler.target>-->
<!--        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>-->

<!--        &lt;!&ndash; Versions &ndash;&gt;-->
<!--        <selenium.version>4.16.1</selenium.version>-->
<!--        <cucumber.version>7.15.0</cucumber.version>-->
<!--        <testng.version>7.9.0</testng.version>-->
<!--        <webdrivermanager.version>5.6.3</webdrivermanager.version>-->
<!--    </properties>-->

<!--    <dependencies>-->
<!--        &lt;!&ndash; Extent Reports Core &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>com.aventstack</groupId>-->
<!--            <artifactId>extentreports</artifactId>-->
<!--            <version>5.1.1</version>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Extent Cucumber 7 Adapter &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>tech.grasshopper</groupId>-->
<!--            <artifactId>extentreports-cucumber7-adapter</artifactId>-->
<!--            <version>1.14.0</version>-->
<!--        </dependency>-->
<!--        &lt;!&ndash; Cucumber &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>io.cucumber</groupId>-->
<!--            <artifactId>cucumber-java</artifactId>-->
<!--            <version>${cucumber.version}</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>io.cucumber</groupId>-->
<!--            <artifactId>cucumber-testng</artifactId>-->
<!--            <version>${cucumber.version}</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

<!--        <dependency>-->
<!--            <groupId>io.cucumber</groupId>-->
<!--            <artifactId>cucumber-picocontainer</artifactId>-->
<!--            <version>${cucumber.version}</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Selenium &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.seleniumhq.selenium</groupId>-->
<!--            <artifactId>selenium-java</artifactId>-->
<!--            <version>${selenium.version}</version>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; TestNG &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.testng</groupId>-->
<!--            <artifactId>testng</artifactId>-->
<!--            <version>${testng.version}</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; WebDriverManager &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>io.github.bonigarcia</groupId>-->
<!--            <artifactId>webdrivermanager</artifactId>-->
<!--            <version>${webdrivermanager.version}</version>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Logging &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>org.slf4j</groupId>-->
<!--            <artifactId>slf4j-simple</artifactId>-->
<!--            <version>2.0.9</version>-->
<!--            <scope>test</scope>-->
<!--        </dependency>-->

<!--        &lt;!&ndash; Data Faker &ndash;&gt;-->
<!--        <dependency>-->
<!--            <groupId>net.datafaker</groupId>-->
<!--            <artifactId>datafaker</artifactId>-->
<!--            <version>2.1.0</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>tech.grasshopper</groupId>-->
<!--            <artifactId>extentreports-cucumber7-adapter</artifactId>-->
<!--            <version>1.14.0</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>commons-io</groupId>-->
<!--            <artifactId>commons-io</artifactId>-->
<!--            <version>2.21.0</version>-->
<!--            <scope>compile</scope>-->
<!--        </dependency>-->

<!--    </dependencies>-->

<!--    <build>-->
<!--        <plugins>-->

<!--            &lt;!&ndash; Compiler Plugin &ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-compiler-plugin</artifactId>-->
<!--                <version>3.13.0</version>-->
<!--                <configuration>-->
<!--                    <source>17</source>-->
<!--                    <target>17</target>-->
<!--                </configuration>-->
<!--            </plugin>-->

<!--            &lt;!&ndash; Surefire Plugin &ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>org.apache.maven.plugins</groupId>-->
<!--                <artifactId>maven-surefire-plugin</artifactId>-->
<!--                <version>3.2.5</version>-->
<!--                <configuration>-->
<!--                    <parallel>methods</parallel>-->
<!--                    <threadCount>4</threadCount>-->
<!--                    <perCoreThreadCount>false</perCoreThreadCount>-->
<!--                    <testFailureIgnore>false</testFailureIgnore>-->
<!--                    <includes>-->
<!--                        <include>**/TestRunner.java</include>-->
<!--                    </includes>-->
<!--                    <systemPropertyVariables>-->
<!--                        <cucumber.publish.quiet>true</cucumber.publish.quiet>-->
<!--                    </systemPropertyVariables>-->
<!--                </configuration>-->
<!--            </plugin>-->

<!--            &lt;!&ndash; Cucumber HTML Reporting &ndash;&gt;-->
<!--            <plugin>-->
<!--                <groupId>net.masterthought</groupId>-->
<!--                <artifactId>maven-cucumber-reporting</artifactId>-->
<!--                <version>5.7.8</version>-->
<!--                <executions>-->
<!--                    <execution>-->
<!--                        <id>execution</id>-->
<!--                        <phase>verify</phase>-->
<!--                        <goals>-->
<!--                            <goal>generate</goal>-->
<!--                        </goals>-->
<!--                        <configuration>-->
<!--                            <projectName>Cucumber Test Report</projectName>-->
<!--                            <outputDirectory>${project.build.directory}</outputDirectory>-->
<!--                            <inputDirectory>${project.build.directory}</inputDirectory>-->
<!--                            <jsonFiles>-->
<!--                                <param>**/*.json</param>-->
<!--                            </jsonFiles>-->
<!--                        </configuration>-->
<!--                    </execution>-->
<!--                </executions>-->
<!--            </plugin>-->

<!--        </plugins>-->
<!--    </build>-->

<!--</project>-->



